// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEZpAhAO17ZKnAV9BeDKIKzJs73w704zA',
    appId: '1:966666011561:web:f56b81a94ee5a83daf3ab8',
    messagingSenderId: '966666011561',
    projectId: 'cesenaremembers1945',
    authDomain: 'cesenaremembers1945.firebaseapp.com',
    storageBucket: 'cesenaremembers1945.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBDO1gfGazsXDkDL_GXR1Vmfcj3LN6qpI',
    appId: '1:966666011561:android:c7b3b729dac06879af3ab8',
    messagingSenderId: '966666011561',
    projectId: 'cesenaremembers1945',
    storageBucket: 'cesenaremembers1945.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0NzLCXUvIhTny4Ma3s32dm09HG5bUewM',
    appId: '1:966666011561:ios:d7e5a68354b330a5af3ab8',
    messagingSenderId: '966666011561',
    projectId: 'cesenaremembers1945',
    storageBucket: 'cesenaremembers1945.firebasestorage.app',
    iosBundleId: 'com.example.cesenaRemembers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0NzLCXUvIhTny4Ma3s32dm09HG5bUewM',
    appId: '1:966666011561:ios:d7e5a68354b330a5af3ab8',
    messagingSenderId: '966666011561',
    projectId: 'cesenaremembers1945',
    storageBucket: 'cesenaremembers1945.firebasestorage.app',
    iosBundleId: 'com.example.cesenaRemembers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEZpAhAO17ZKnAV9BeDKIKzJs73w704zA',
    appId: '1:966666011561:web:91b0fe1676a194fbaf3ab8',
    messagingSenderId: '966666011561',
    projectId: 'cesenaremembers1945',
    authDomain: 'cesenaremembers1945.firebaseapp.com',
    storageBucket: 'cesenaremembers1945.firebasestorage.app',
  );
}
